version: 2
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go generate ./internal/loldrivers/
    - go test ./internal/loldrivers/
builds:
  - id: windows
    ldflags:
      - -s -w
    binary: 'LOLDrivers-client'
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - 
    formats: zip
    name_template: >-
      LOLDrivers-client_Windows_{{ .Arch }}
    files:
      - "README.md"
      - "LICENSE"