version: 2
env:
  - CGO_ENABLED=1
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go test ./pkg/loldrivers/ -v -cover
builds:
  - id: windows
    ldflags:
      - -s -w
    binary: 'LOLDrivers-client'
    main: ./cmd/loldrivers-client/loldrivers-client.go
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - 
    formats: zip
    name_template: >-
      LOLDrivers-client_Windows_{{ .Arch }}
    files:
      - "README.md"
      - "LICENSE"