version: 2
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go generate ./internal/loldrivers/
    - go test ./internal/loldrivers/
builds:
  - id: windows
    ldflags:
      - -s -w
    binary: 'LOLDrivers-client'
    goos:
      - windows
    goarch:
      - amd64
      - arm64
  - id: windows_embedded
    ldflags:
      - -s -w
    binary: 'LOLDrivers-client_embedded'
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    tags:
      - embedded

archives:
  - id: windows
    ids:
      - windows
    formats:
      - zip
    name_template: 'LOLDrivers-client_Windows_{{ .Arch }}'
    files:
      - "README.md"
      - "LICENSE"
  - id: windows_embedded
    ids:
      - windows_embedded
    formats:
      - zip
    name_template: 'LOLDrivers-client_Windows_{{ .Arch }}_embedded'
    files:
      - "README.md"
      - "LICENSE"